# Generated by Django 4.2.4 on 2023-08-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('descp', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='movies/image')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
